- name: Get all static files
  django_manage:
    app_path: "{{ src_directory }}"
    command: collectstatic
    virtualenv: "{{ venv_directory }}"
  become: true
  notify:
    - restart app
    - restart nginx

- name: Change permissions for the static directory
  file:
    path: "{{ static_directory }}"
    owner: "www-data"
    recurse: yes
    state: directory
    mode: 0744