# Generated by Django 3.2.5 on 2022-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
