# Generated by Django 3.2.5 on 2022-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_publication_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="publication_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="file",
            field=models.FileField(upload_to="publications/"),
        ),
    ]
