# Generated by Django 3.2.5 on 2022-05-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_auto_20220426_1710"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="preview",
            field=models.FileField(null=True, upload_to="publications/"),
        ),
    ]
