# Generated by Django 3.0.5 on 2020-08-11 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0002_remove_document_origassign_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="archive",
        ),
        migrations.AddField(
            model_name="archive",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb20.Document",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb20.Location",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="location",
            field=models.ManyToManyField(
                through="hueb20.Archive", to="hueb20.Location"
            ),
        ),
    ]
