# Generated by Django 3.0.5 on 2020-08-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_latein", "0005_auto_20200709_2025"),
        ("hueb20", "0004_auto_20200811_2137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="locAssign_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy_latein.LocAssign",
            ),
        ),
    ]
