# Generated by Django 3.0.5 on 2020-07-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0006_auto_20200812_1137"),
    ]

    operations = []
