# Generated by Django 3.0.5 on 2020-07-09 21:55

from django.db import migrations


def load_countries(apps, schema_editor):
    Country_legacy = apps.get_model("hueb_legacy_latein", "Country")

    Country = apps.get_model("hueb20", "Country")
    Source = apps.get_model("hueb20", "SourceReference")

    for legacy_country in Country_legacy.objects.all():
        source = Source()
        source.app = "hueb_legacy_latein"
        source.country_ref = legacy_country
        source.save()

        new_country = Country()
        new_country.id = legacy_country.id
        new_country.country = legacy_country.country
        new_country.source = source
        new_country.save()


def unload_countries(apps, schema_editor):
    Source = apps.get_model("hueb20", "SourceReference")
    Source.objects.filter(app="hueb_legacy_latein").filter(
        country_ref__isnull=False
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0006_base"),
        ("hueb_legacy_latein", "0005_auto_20200709_2025"),
    ]

    operations = [migrations.RunPython(load_countries, unload_countries)]
