# Generated by Django 3.0.5 on 2020-08-14 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0008_auto_20200814_2004"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="translated_from",),
        migrations.RemoveField(model_name="document", name="translated_to",),
        migrations.CreateModel(
            name="DocumentRelationship",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("TRANSL", "Translation"),
                            ("ORIGIN", "Original"),
                            ("BRIDGE", "Bridge"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("LATEIN", "HÜB Latein Datensatz"),
                            ("LIDOS ", "HÜB Lidos Datensatz"),
                            ("LEGACY", "HÜB Basis Datensatz"),
                            ("HUEB20", "HÜB 2020 Datensatz"),
                        ],
                        default="HUEB20",
                        max_length=6,
                    ),
                ),
                (
                    "document_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="source",
                        to="hueb20.Document",
                    ),
                ),
                (
                    "document_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="target",
                        to="hueb20.Document",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="document_relationships",
            field=models.ManyToManyField(
                related_name="_document_document_relationships_+",
                through="hueb20.DocumentRelationship",
                to="hueb20.Document",
            ),
        ),
    ]
