# Generated by Django 3.0.5 on 2020-07-09 21:55

from django.db import migrations


def load_languages(apps, schema_editor):
    Legacy_Language = apps.get_model("hueb_legacy_latein", "Language")

    Language = apps.get_model("hueb20", "Language")

    for legacy_language in Legacy_Language.objects.all():

        new_language = Language()
        # Set reference to old entries
        new_language.language_ref = legacy_language
        new_language.app = "hueb_legacy_latein"

        # transfer information
        new_language.language = legacy_language.language

        # save new model
        new_language.save()


def unload_languages(apps, schema_editor):
    Language = apps.get_model("hueb20", "Language")
    Language.objects.filter(app="hueb_legacy_latein").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0010_load_people"),
        ("hueb_legacy_latein", "0005_auto_20200709_2025"),
    ]

    operations = [migrations.RunPython(load_languages, unload_languages)]
