# Generated by Django 3.0.5 on 2020-07-09 21:55

from django.db import migrations


def load_origAssign(apps, schema_editor):
    OrigAssign = apps.get_model("hueb_legacy_latein", "OrigAssign")
    Document = apps.get_model("hueb20", "Document")
    for relationship in (
        OrigAssign.objects.filter(orig_new__isnull=False)
        .filter(trans_new__isnull=False)
        .all()
    ):
        original = Document.objects.get(original_ref=relationship.orig_new_id)
        translation = Document.objects.get(translation_ref=relationship.trans_new_id)
        original.translated_to.add(translation)
        original.save()
        translation.translated_from.add(original)
        translation.save()


def unload_origAssign(apps, schema_editor):
    Document = apps.get_model("hueb20", "Document")
    Document.translated_from.through.objects.all().delete()
    Document.translated_to.through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0012_load_documents"),
        ("hueb_legacy_latein", "0005_auto_20200709_2025"),
    ]

    operations = [migrations.RunPython(load_origAssign, unload_origAssign)]
