# Generated by Django 3.0.5 on 2020-07-09 21:55

from django.db import migrations


def load_locAssign(apps, schema_editor):
    LocAssign = apps.get_model("hueb_legacy_latein", "LocAssign")
    Document = apps.get_model("hueb20", "Document")
    Archive = apps.get_model("hueb20", "Archive")
    Location = apps.get_model("hueb20", "Location")

    for relationship in (
        LocAssign.objects.filter(loc_new__isnull=False)
        .filter(trans_new__isnull=False)
        .all()
    ):
        location = Location.objects.get(location_ref=relationship.loc_new_id)
        translation = Document.objects.get(translation_ref=relationship.trans_new_id)
        archive = Archive.objects.create(
            location=location,
            document=translation,
            signatur=relationship.signatur,
            locAssign_ref=relationship,
            link=translation.translation_ref.link,
            app="hueb_legacy_latein",
        )
        archive.save()

    for relationship in (
        LocAssign.objects.filter(loc_new__isnull=False)
        .filter(orig_new__isnull=False)
        .all()
    ):
        location = Location.objects.get(location_ref=relationship.loc_new_id)
        original = Document.objects.get(original_ref=relationship.orig_new_id)
        archive = Archive.objects.create(
            location=location,
            document=original,
            signatur=relationship.signatur,
            locAssign_ref=relationship,
            link=original.original_ref.link,
            app="hueb_legacy_latein",
        )
        archive.save()


def unload_locAssign(apps, schema_editor):
    Archive = apps.get_model("hueb20", "Archive")
    Archive.objects.filter(app="hueb_legacy_latein").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0013_load_document_relationships"),
        ("hueb_legacy_latein", "0005_auto_20200709_2025"),
    ]

    operations = [migrations.RunPython(load_locAssign, unload_locAssign)]
