# Generated by Django 3.0.5 on 2020-08-14 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0010_remove_documentrelationship_relationship_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ddcgerman",
            options={"verbose_name": "DDC", "verbose_name_plural": "DDCs"},
        ),
        migrations.RemoveField(
            model_name="person",
            name="lifetime",
        ),
        migrations.AddField(
            model_name="yearrange",
            name="lifetime",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lifetime",
                to="hueb20.Person",
            ),
        ),
    ]
