# Generated by Django 3.0.5 on 2020-08-16 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0018_auto_20200816_1837"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yearrange",
            name="end_uncertainty",
        ),
        migrations.RemoveField(
            model_name="yearrange",
            name="start_uncertainty",
        ),
        migrations.AddField(
            model_name="yearrange",
            name="end",
            field=models.CharField(
                default="0000",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "Only 0-9 are allowed.", "Invalid Number"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yearrange",
            name="start",
            field=models.CharField(
                default="0001",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "Only 0-9 are allowed.", "Invalid Number"
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
