# Generated by Django 3.0.5 on 2020-08-22 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0019_auto_20200816_1912"),
    ]

    operations = [migrations.RenameModel("Archive", "Filing")]
