# Generated by Django 3.0.5 on 2020-08-22 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0020_auto_20200822_0838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filing",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hueb20.Document",
            ),
        ),
        migrations.AlterField(
            model_name="filing",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hueb20.Location",
            ),
        ),
    ]
