# Generated by Django 3.0.5 on 2020-08-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_latein", "0006_auto_20200814_1826"),
        ("hueb20", "0022_auto_20200822_0936"),
    ]

    operations = [
        migrations.RenameModel(old_name="Location", new_name="Archive",),
        migrations.RenameField(
            model_name="filing", old_name="location", new_name="archive",
        ),
    ]
