# Generated by Django 3.0.5 on 2020-08-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0023_auto_20200822_1007"),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalCircle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the cultural circle", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("LATEIN", "HÜB Latein Datensatz"),
                            ("LIDOS ", "HÜB Lidos Datensatz"),
                            ("LEGACY", "HÜB Basis Datensatz"),
                            ("HUEB20", "HÜB 2020 Datensatz"),
                        ],
                        default="HUEB20",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="document", name="country",),
        migrations.AddField(
            model_name="document",
            name="cultural_circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb20.CulturalCircle",
            ),
        ),
    ]
