# Generated by Django 3.0.5 on 2020-07-09 21:55

from django.db import migrations
from hueb.apps.hueb20.models import LATEIN


def load_cultural_circles(apps, schema_editor):
    Country_legacy = apps.get_model("hueb_legacy_latein", "Country")

    CulturalCircle = apps.get_model("hueb20", "CulturalCircle")

    for legacy_country in Country_legacy.objects.all():

        new_cultural_circle = CulturalCircle()
        # Set reference to old entries
        new_cultural_circle.country_ref = legacy_country
        new_cultural_circle.app = LATEIN

        # transfer information
        new_cultural_circle.name = legacy_country.country

        # save new model
        new_cultural_circle.save()


def unload_cultural_circles(apps, schema_editor):
    CulturalCircle = apps.get_model("hueb20", "CulturalCircle")
    CulturalCircle.objects.filter(app=LATEIN).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0024_auto_20200822_1153"),
        ("hueb_legacy_latein", "0005_auto_20200709_2025"),
    ]

    operations = [migrations.RunPython(load_cultural_circles, unload_cultural_circles)]
