# Generated by Django 3.0.5 on 2020-08-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0024_auto_20200822_1153"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearrange",
            name="culturalCircleTimeRange",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="culturalCircleTimeRange",
                to="hueb20.CulturalCircle",
            ),
        ),
    ]
