# Generated by Django 3.0.5 on 2020-08-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0026_yearrange_culturalcircletimerange"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="external",
            field=models.BooleanField(
                default=False,
                help_text="External comments will be displayed on the public website.",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_comment",
                to="hueb20.Document",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_comment",
                to="hueb20.Person",
            ),
        ),
    ]
