# Generated by Django 3.0.5 on 2020-08-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0027_auto_20200822_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="cultural_circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cultural_circle_comment",
                to="hueb20.CulturalCircle",
            ),
        ),
    ]
