# Generated by Django 3.0.5 on 2020-08-25 21:10

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0028_comment_cultural_circle"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="real_year",),
        migrations.RemoveField(model_name="document", name="year",),
        migrations.AddField(
            model_name="culturalcircle",
            name="end",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="culturalcircle",
            name="start",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="written_in",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="lifetime_end",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="lifetime_start",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(
                blank=True, null=True
            ),
        ),
        migrations.DeleteModel(name="YearRange",),
    ]
