# Generated by Django 3.0.5 on 2020-10-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0032_auto_20201002_1128"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="document_relationships",),
        migrations.AddField(
            model_name="document",
            name="translations",
            field=models.ManyToManyField(
                related_name="originals",
                through="hueb20.DocumentRelationship",
                to="hueb20.Document",
            ),
        ),
        migrations.AlterField(
            model_name="documentrelationship",
            name="document_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="to_original",
                to="hueb20.Document",
            ),
        ),
        migrations.AlterField(
            model_name="documentrelationship",
            name="document_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="to_translation",
                to="hueb20.Document",
            ),
        ),
    ]
