# Generated by Django 3.0.5 on 2020-07-09 21:55

from django.db import migrations
from hueb.apps.hueb20.models.utils import close_range, open_range


def correct_date_ranges(apps, schema_editor):
    Document = apps.get_model("hueb20", "Document")
    Person = apps.get_model("hueb20", "Person")

    for document in Document.objects.all():
        document.written_in = close_range(document.written_in)
        document.save()

    for person in Person.objects.all():
        person.lifetime_start = close_range(person.lifetime_start)
        person.lifetime_end = close_range(person.lifetime_end)
        person.save()


def uncorrect_date_ranges(apps, schema_editor):
    Document = apps.get_model("hueb20", "Document")
    Person = apps.get_model("hueb20", "Person")

    for document in Document.objects.all():
        document.written_in = open_range(document.written_in)
        document.save()

    for person in Person.objects.all():
        person.lifetime_start = open_range(person.lifetime_start)
        person.lifetime_end = open_range(person.lifetime_end)
        person.save


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0033_auto_20201019_1145"),
    ]

    operations = [migrations.RunPython(correct_date_ranges, uncorrect_date_ranges)]
