# Generated by Django 3.1.3 on 2021-02-07 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0039_auto_20210207_1653"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="archive",
        ),
        migrations.RemoveField(
            model_name="review",
            name="country",
        ),
        migrations.RemoveField(
            model_name="review",
            name="cultural_circle",
        ),
        migrations.RemoveField(
            model_name="review",
            name="ddc_german",
        ),
        migrations.RemoveField(
            model_name="review",
            name="document",
        ),
        migrations.RemoveField(
            model_name="review",
            name="filing",
        ),
        migrations.RemoveField(
            model_name="review",
            name="note",
        ),
        migrations.RemoveField(
            model_name="review",
            name="person",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.DeleteModel(
            name="HistoricalReview",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
