# Generated by Django 3.1.3 on 2021-02-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0043_create_contributions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archive",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="contribution",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="culturalcircle",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="documentrelationship",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="filing",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"permissions": [("can_review", "Can review hueb entries")]},
        ),
    ]
