# Generated by Django 3.2.5 on 2021-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0046_fill_written_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="contributions",
            field=models.ManyToManyField(
                related_name="documents",
                through="hueb20.Contribution",
                to="hueb20.Person",
            ),
        ),
    ]
