# Generated by Django 3.2.5 on 2021-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueb20', '0055_load_latein_originals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallanguage',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
    ]
