# Generated by Django 3.2.5 on 2021-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0056_auto_20211220_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallanguage",
            name="language",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(max_length=255),
        ),
    ]
