# Generated by Django 3.0.5 on 2020-07-09 21:55

from django.db import migrations
from hueb.apps.hueb20.models import LATEIN


def load_online_filings(apps, schema_editor):
    Filing = apps.get_model("hueb20", "Filing")
    Document = apps.get_model("hueb20", "Document")
    Archive = apps.get_model("hueb20", "Archive")
    Latein_originals = apps.get_model("hueb_legacy_latein", "OriginalNew")
    Latein_translations = apps.get_model("hueb_legacy_latein", "TranslationNew")
    #online_arch = Archive.objects.get(name="Online-Version")

    #for fil in Filing.objects.filter(app=LATEIN).exclude(archive=online_arch).all():
    for fil in Filing.objects.filter(app=LATEIN).exclude(archive__name="Online-Version").all():
        fil.link = None
        fil.save()

    for org in Latein_originals.objects.all():
        if org.link is not None and org.link != "":
            new_filing = Filing()
            new_filing.app = LATEIN

            new_filing.archive = Archive.objects.get(name="Online-Version")
            new_filing.document = Document.objects.get(original_ref=org)
            new_filing.link = org.link
            new_filing.save()
    for trans in Latein_translations.objects.all():
        if trans.link is not None and trans.link != "":
            new_filing = Filing()
            new_filing.app = LATEIN
            new_filing.ref = trans

            new_filing.archive = Archive.objects.get(name="Online-Version")
            new_filing.document = Document.objects.get(translation_ref=trans)
            new_filing.link = trans.link
            new_filing.save()

def unload_online_filings(apps, schema_editor):
    Filing = apps.get_model("hueb20", "Filing")
    Archive = apps.get_model("hueb20", "Archive")
    online_arch = Archive.objects.get(name="Online-Version")
    Filing.objects.filter(app=LATEIN).filter(archive=online_arch).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0064_update_no_pairs"),
    ]

    operations = [migrations.RunPython(load_online_filings, unload_online_filings)]
