# Generated by Django 3.2.5 on 2022-02-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "hueb_legacy_latein",
            "0009_rename_original_new_originalnewauthornew_original",
        ),
        ("hueb20", "0077_legacy_authors_transators"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="locAssign_legacy_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hueb20_filing_set",
                to="hueb_legacy_latein.locassign",
            ),
        ),
        migrations.AddField(
            model_name="historicalfiling",
            name="locAssign_legacy_ref",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hueb_legacy_latein.locassign",
            ),
        ),
    ]
