# Generated by Django 3.2.5 on 2022-03-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0088_lidos_trans_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="language_orig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="temp_originals",
                to="hueb20.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="language_orig",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hueb20.language",
            ),
        ),
    ]
