# Generated by Django 3.2.5 on 2022-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0093_fill_cc_tempname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="culturalcircle",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalculturalcircle",
            name="name",
        ),
        migrations.AddField(
            model_name="culturalcircle",
            name="name_de",
            field=models.CharField(
                help_text="Name of the cultural circle",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="culturalcircle",
            name="name_en",
            field=models.CharField(
                help_text="Name of the cultural circle",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="historicalculturalcircle",
            name="name_de",
            field=models.CharField(
                help_text="Name of the cultural circle",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="historicalculturalcircle",
            name="name_en",
            field=models.CharField(
                help_text="Name of the cultural circle",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
