# Generated by Django 3.2.5 on 2022-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueb20', '0095_fill_translated_cc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddcgerman',
            name='ddc_name_temp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalddcgerman',
            name='ddc_name_temp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
