# Generated by Django 3.2.5 on 2022-04-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0099_fill_translated_ddc_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="language_temp",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicallanguage",
            name="language_temp",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicallanguage",
            name="language",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
