# Generated by Django 3.0.5 on 2020-07-09 21:55

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def fill_main_author(apps, schema_editor):
    Document = apps.get_model("hueb20", "Document")

    for doc in Document.objects.all():
        if doc.contribution_set.filter(contribution_type="WRITER").exists():
            doc.main_author = (
                doc.contribution_set.filter(contribution_type="WRITER")
                .order_by(F("person__name").asc(nulls_last=True))
                .first()
                .person
            )
            doc.save()


def remove_main_author(apps, schema_editor):
    Document = apps.get_model("hueb20", "Document")

    for doc in Document.objects.all():
        doc.main_author = None
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0105_online_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="main_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb20.person",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="main_author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hueb20.person",
            ),
        ),
        migrations.RunPython(fill_main_author, remove_main_author),
    ]
