# Generated by Django 3.2.5 on 2022-09-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0107_fill_main_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filing",
            name="link",
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfiling",
            name="link",
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
