# Generated by Django 3.2.5 on 2022-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0108_auto_20220919_0810"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="link_status",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalfiling",
            name="link_status",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
