# Generated by Django 3.2.5 on 2023-02-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_create_tenants"),
        ("hueb20", "0115_move_cultural_circles"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenants.tenant",
            ),
        ),
    ]
