# Generated by Django 3.2.5 on 2023-02-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantuser"),
        ("hueb20", "0116_auto_20230217_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
    ]
