# Generated by Django 3.2.5 on 2023-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb20", "0117_alter_document_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="app",
            field=models.CharField(
                choices=[
                    ("LATEIN", "HÜB Latein Datensatz"),
                    ("LIDOS", "HÜB Lidos Datensatz"),
                    ("LEGACY", "HÜB Basis Datensatz"),
                    ("HUEB20", "HÜB 2020 Datensatz"),
                    ("GUEBFR", "GÜB-FR"),
                ],
                default="HUEB20",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="app",
            field=models.CharField(
                choices=[
                    ("LATEIN", "HÜB Latein Datensatz"),
                    ("LIDOS", "HÜB Lidos Datensatz"),
                    ("LEGACY", "HÜB Basis Datensatz"),
                    ("HUEB20", "HÜB 2020 Datensatz"),
                    ("GUEBFR", "GÜB-FR"),
                ],
                default="HUEB20",
                max_length=6,
            ),
        ),
    ]
