# Generated by Django 3.2.5 on 2023-04-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantuser"),
        ("hueb20", "0119_auto_20230401_1120"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="app",
            field=models.CharField(
                choices=[
                    ("LATEIN", "SÜB-Lat"),
                    ("LIDOS", "DFÜ-FR"),
                    ("LEGACY", "SÜB-Rom"),
                    ("HUEB20", "HÜB-EN-NL"),
                    ("GUEBFR", "GÜB-FR"),
                ],
                default="HUEB20",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="app",
            field=models.CharField(
                choices=[
                    ("LATEIN", "SÜB-Lat"),
                    ("LIDOS", "DFÜ-FR"),
                    ("LEGACY", "SÜB-Rom"),
                    ("HUEB20", "HÜB-EN-NL"),
                    ("GUEBFR", "GÜB-FR"),
                ],
                default="HUEB20",
                max_length=6,
            ),
        ),
    ]
