# Generated by Django 3.2.5 on 2024-09-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0134_auto_20240727_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="duplicates",
            field=models.ManyToManyField(
                related_name="_hueb20_person_duplicates_+", to="hueb20.Person"
            ),
        ),
    ]
