# Generated by Django 3.2.5 on 2024-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb20", "0135_person_duplicates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="duplicates",
            field=models.ManyToManyField(
                blank=True,
                related_name="_hueb20_person_duplicates_+",
                to="hueb20.Person",
            ),
        ),
    ]
