# Generated by Django 3.2.5 on 2021-07-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuebAuthor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_author",
            },
        ),
        migrations.CreateModel(
            name="SuebCollection",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("editor", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_collection",
            },
        ),
        migrations.CreateModel(
            name="SuebCountry",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=255)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_country",
            },
        ),
        migrations.CreateModel(
            name="SuebDdcGerman",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("ddc_number", models.CharField(max_length=3)),
                ("ddc_name", models.CharField(max_length=255)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_ddc_german",
            },
        ),
        migrations.CreateModel(
            name="SuebLanguage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("language", models.CharField(max_length=255)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_language",
            },
        ),
        migrations.CreateModel(
            name="SuebPndMain",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("person", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_pnd_main",
            },
        ),
        migrations.CreateModel(
            name="SuebSwdMain",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "number_800_hauptschlagwort",
                    models.CharField(
                        blank=True,
                        db_column="800_hauptschlagwort",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_801_unterschlagwort1",
                    models.CharField(
                        blank=True,
                        db_column="801_unterschlagwort1",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_802_unterschlagwort2",
                    models.CharField(
                        blank=True,
                        db_column="802_unterschlagwort2",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_swd_main",
            },
        ),
        migrations.CreateModel(
            name="SuebManualKeys",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("term", models.CharField(max_length=255)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_manual_keys",
            },
        ),
        migrations.CreateModel(
            name="SuebTranslator",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
            ],
            options={
                "db_table": "sueb_translator",
            },
        ),
        migrations.CreateModel(
            name="SuebTranslation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField(blank=True, null=True)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("year", models.CharField(blank=True, max_length=100, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "published_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("edition", models.TextField(blank=True, null=True)),
                ("language_id", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("real_year", models.IntegerField(blank=True, null=True)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebauthor",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebcollection",
                    ),
                ),
                (
                    "ddc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebddcgerman",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebtranslator",
                    ),
                ),
                (
                    "via_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.sueblanguage",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_translation",
            },
        ),
        migrations.CreateModel(
            name="SuebSwdTerm",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "number_820_alternativform",
                    models.CharField(
                        blank=True,
                        db_column="820_alternativform",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_830_aequivalentebezeichnung",
                    models.CharField(
                        blank=True,
                        db_column="830_aequivalentebezeichnung",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_845_oberbegriff",
                    models.CharField(
                        blank=True,
                        db_column="845_oberbegriff",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_850_uebergeordnetesschlagwort",
                    models.CharField(
                        blank=True,
                        db_column="850_uebergeordnetesschlagwort",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_860_verwandtesschlagwort",
                    models.CharField(
                        blank=True,
                        db_column="860_verwandtesschlagwort",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "swd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebswdmain",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_swd_term",
            },
        ),
        migrations.CreateModel(
            name="SuebPndTitle",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("pnd_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "pnd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebpndmain",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_pnd_title",
            },
        ),
        migrations.CreateModel(
            name="SuebPndAlias",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("pnd_alias", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "pnd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebpndmain",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_pnd_alias",
            },
        ),
        migrations.CreateModel(
            name="SuebOriginal",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField(blank=True, null=True)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("year", models.CharField(blank=True, max_length=100, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "published_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("edition", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("real_year", models.IntegerField(blank=True, null=True)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebauthor",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebcollection",
                    ),
                ),
                (
                    "ddc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebddcgerman",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.sueblanguage",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_original",
            },
        ),
        migrations.CreateModel(
            name="SuebOrigAssign",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.sueboriginal",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebtranslation",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_orig_assign",
            },
        ),
        migrations.CreateModel(
            name="SuebLocation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("adress", models.TextField(blank=True, null=True)),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                ("ip", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "z3950_gateway",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebcountry",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_location",
            },
        ),
        migrations.CreateModel(
            name="SuebLocAssign",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("signatur", models.CharField(max_length=255)),
                (
                    "migration_notes",
                    models.CharField(blank=True, max_length=1023, null=True),
                ),
                ("migration_generated", models.BooleanField()),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.sueblocation",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.sueboriginal",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hueb_legacy.suebtranslation",
                    ),
                ),
            ],
            options={
                "db_table": "sueb_loc_assign",
            },
        ),
        migrations.AddField(
            model_name="suebmanualkeys",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.sueboriginal",
            ),
        ),
        migrations.AddField(
            model_name="suebmanualkeys",
            name="translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.suebtranslation",
            ),
        ),
    ]
