# Generated by Django 3.2.5 on 2021-07-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb_legacy", "0002_auto_20210707_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ddcgerman",
            name="ddc_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ddcgerman",
            name="ddc_number",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="ddcgerman",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locassign",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locassign",
            name="signatur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="origassign",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="original",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.author",
            ),
        ),
        migrations.AlterField(
            model_name="original",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pndalias",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pndalias",
            name="pnd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.pndmain",
            ),
        ),
        migrations.AlterField(
            model_name="pndmain",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pndtitle",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="swdmain",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="swdterm",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="swdterm",
            name="swd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.swdmain",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="translator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.translator",
            ),
        ),
        migrations.AlterField(
            model_name="translator",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="translator",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
