# Generated by Django 3.2.5 on 2021-07-07 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb_legacy", "0004_auto_20210707_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualkeys",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.original",
            ),
        ),
        migrations.AlterField(
            model_name="manualkeys",
            name="translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.translation",
            ),
        ),
        migrations.AlterField(
            model_name="manualkeys",
            name="migration_generated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manualkeys",
            name="term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
