# Generated by Django 3.2.5 on 2021-07-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy", "0005_auto_20210707_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="language_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy.language",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="via_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="BridgeLanguage",
                to="hueb_legacy.language",
            ),
        ),
    ]
