# Generated by Django 3.2.5 on 2021-07-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy", "0006_auto_20210707_1537"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translation",
            old_name="language_id",
            new_name="language",
        ),
    ]
