# Generated by Django 3.2.5 on 2023-02-12 16:30

from django.db import migrations, models
from hueb.apps.tenants.models import TENANT_APPS


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subdomain_prefix", models.CharField(max_length=100, unique=True)),
                ("app", models.CharField(max_length=6, choices=TENANT_APPS)),
            ],
        ),
    ]
