# Generated by Django 3.2.5 on 2023-07-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0004_create_tenants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenantuser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
