from .archive import ArchiveAdmin
from .comment import CommentAdmin
from .country import CountryAdmin
from .culturalCircle import CulturalCircleAdmin
from .ddc import DdcGermanAdmin
from .document import DocumentAdmin
from .filing import FilingAdmin
from .language import LanguageAdmin
from .person import PersonAdmin
