# Generated by Django 3.2.5 on 2021-07-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_lidos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translation",
            old_name="manual_keys",
            new_name="manual_keys_id",
        ),
    ]
