# Generated by Django 3.2.5 on 2021-07-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hueb_legacy_lidos", "0002_rename_manual_keys_translation_manual_keys_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translation",
            old_name="manual_keys_id",
            new_name="manual_keys",
        ),
        migrations.AlterField(
            model_name="translation",
            name="language_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy_lidos.language",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="via_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bridgeTranslation",
                to="hueb_legacy_lidos.language",
            ),
        ),
    ]
