# Generated by Django 3.2.5 on 2021-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_lidos", "0004_rename_language_id_translation_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ddcgerman",
            options={"verbose_name_plural": "DDC German"},
        ),
        migrations.AlterModelOptions(
            name="lidosex",
            options={"verbose_name_plural": "Lidos Ex"},
        ),
        migrations.AlterModelOptions(
            name="manualkeys",
            options={"verbose_name_plural": "Manual keys"},
        ),
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ddcgerman",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="filter",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="language",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lidosex",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="manualkeys",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="origassign",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="original",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="translation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="translator",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
