# Generated by Django 3.2.5 on 2021-07-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_lidos", "0006_auto_20210707_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="translator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy_lidos.translator",
            ),
        ),
    ]
