# Generated by Django 3.2.5 on 2021-07-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_lidos", "0007_alter_translation_translator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manualkeys",
            name="term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="original",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hueb_legacy_lidos.author",
            ),
        ),
        migrations.AlterField(
            model_name="translator",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
