# Generated by Django 3.2.5 on 2021-07-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_lidos", "0008_auto_20210707_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="original",
            name="manual_keys",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="OriginalManualKeys",
                to="hueb_legacy_lidos.manualkeys",
            ),
        ),
    ]
