# Generated by Django 3.2.5 on 2022-01-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'managed': False},
        ),
    ]
