# Generated by Django 3.2.5 on 2022-01-31 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_history", "0003_link_user_histories"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userhistory",
            table=None,
        ),
    ]
