# Generated by Django 3.2.5 on 2022-01-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_history', '0004_alter_userhistory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={},
        ),
    ]
