# Generated by Django 3.0.5 on 2020-07-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hueb_legacy_latein", "0004_auto_20200417_2001"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "OLD Author"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "COMMON Country"},
        ),
        migrations.AlterModelOptions(
            name="ddcgerman",
            options={"verbose_name_plural": "COMMON DDC"},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name_plural": "COMMON Language"},
        ),
        migrations.AlterModelOptions(
            name="locassign",
            options={"verbose_name_plural": "COMMON LocAssign"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name_plural": "OLD Location"},
        ),
        migrations.AlterModelOptions(
            name="origassign",
            options={"verbose_name_plural": "COMMON OrigAssign"},
        ),
        migrations.AlterModelOptions(
            name="original",
            options={"verbose_name_plural": "OLD Original"},
        ),
        migrations.AlterModelOptions(
            name="translation",
            options={"verbose_name_plural": "OLD Translation"},
        ),
        migrations.AlterModelOptions(
            name="translator",
            options={"verbose_name_plural": "OLD Translator"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "COMMON User"},
        ),
    ]
