# Generated by Django 3.0.5 on 2020-08-22 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hueb_legacy_latein", "0006_auto_20200814_1826"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authornew",
            options={"verbose_name_plural": "Latein Author"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Latein Country"},
        ),
        migrations.AlterModelOptions(
            name="ddcgerman",
            options={"verbose_name_plural": "Latein DDC"},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name_plural": "Latein Language"},
        ),
        migrations.AlterModelOptions(
            name="locassign",
            options={"verbose_name_plural": "Latein LocAssign"},
        ),
        migrations.AlterModelOptions(
            name="locationnew",
            options={"verbose_name_plural": "Latein Location"},
        ),
        migrations.AlterModelOptions(
            name="origassign",
            options={"verbose_name_plural": "Latein OrigAssign"},
        ),
        migrations.AlterModelOptions(
            name="originalnew",
            options={"verbose_name_plural": "Latein Original"},
        ),
        migrations.AlterModelOptions(
            name="translationnew",
            options={"verbose_name_plural": "Latein Translation"},
        ),
        migrations.AlterModelOptions(
            name="translatornew",
            options={"verbose_name_plural": "Latein Translator"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "Latein User"},
        ),
    ]
