# Generated by Django 3.2.5 on 2021-07-16 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hueb_legacy_latein", "0007_auto_20200822_1500"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translationnewtranslatornew",
            old_name="translation_new",
            new_name="translation",
        ),
    ]
