# Generated by Django 3.2.5 on 2021-07-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "hueb_legacy_latein",
            "0008_rename_translation_new_translationnewtranslatornew_translation",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="originalnewauthornew",
            old_name="original_new",
            new_name="original",
        ),
    ]
