# Generated by Django 3.0.5 on 2020-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueb_legacy_latein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='author',
            field=models.ManyToManyField(through='hueb_legacy_latein.OriginalAuthor', to='hueb_legacy_latein.Author'),
        ),
    ]
