# Generated by Django 3.0.5 on 2020-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueb_legacy_latein', '0002_original_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='author_new',
            field=models.ManyToManyField(through='hueb_legacy_latein.OriginalAuthorNew', to='hueb_legacy_latein.AuthorNew'),
        ),
        migrations.AddField(
            model_name='originalnew',
            name='author',
            field=models.ManyToManyField(through='hueb_legacy_latein.OriginalNewAuthor', to='hueb_legacy_latein.Author'),
        ),
        migrations.AddField(
            model_name='originalnew',
            name='author_new',
            field=models.ManyToManyField(through='hueb_legacy_latein.OriginalNewAuthorNew', to='hueb_legacy_latein.AuthorNew'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translator',
            field=models.ManyToManyField(through='hueb_legacy_latein.TranslationTranslator', to='hueb_legacy_latein.Translator'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translator_new',
            field=models.ManyToManyField(through='hueb_legacy_latein.TranslationTranslatorNew', to='hueb_legacy_latein.TranslatorNew'),
        ),
        migrations.AddField(
            model_name='translationnew',
            name='translator',
            field=models.ManyToManyField(through='hueb_legacy_latein.TranslationNewTranslator', to='hueb_legacy_latein.Translator'),
        ),
        migrations.AddField(
            model_name='translationnew',
            name='translator_new',
            field=models.ManyToManyField(through='hueb_legacy_latein.TranslationNewTranslatorNew', to='hueb_legacy_latein.TranslatorNew'),
        ),
    ]
