\set ON_ERROR_STOP true
SET search_path to di_sueb;

-- These calls adds a migration_note attribute to each table.
-- This attribute can be used to explain necessary changes to table entries to allow the foreign key constraint creation.

ALTER TABLE sueb_author
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_collection
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_country
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_ddc_german
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_language
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_loc_assign
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_location
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_manual_keys
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_orig_assign
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_original
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_pnd_alias
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_pnd_main
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_pnd_title
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_swd_main
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_swd_term
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_translation
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sueb_translator
ADD COLUMN IF NOT EXISTS migration_notes VARCHAR(1023),
ADD COLUMN IF NOT EXISTS migration_generated BOOLEAN NOT NULL DEFAULT FALSE;

